#!/bin/bash

CONTAINER_NAME=shell-development

docker run \
    --name $CONTAINER_NAME \
    -d -ti \
    -v ~/.gitconfig:/home/developer/.gitconfig \
    -v ./.ssh:/home/developer/.ssh \
    shell-development:latest \
    zsh

docker exec -ti $CONTAINER_NAME zsh
