#!/bin/bash

CONTAINER_NAME=shell-development

podman run \
    --name $CONTAINER_NAME \
    -d -ti \
    -v ~/.gitconfig:/home/developer/.gitconfig \
    -v ./.ssh:/home/developer/.ssh:U \
    shell-development:latest \
    zsh

podman exec -ti $CONTAINER_NAME zsh
