#!/bin/bash

docker run \
    --name dev \
    -d -ti \
    -v ~/.gitconfig:/home/developer/.gitconfig \
    -v ./.ssh:/home/developer/.ssh \
    my-development-environment:latest \
    zsh

docker exec -ti dev zsh
